stages:
  - test
  - history_copy
  - reports
  - deploy

test_job:
  stage: test

  tags:
    - shell

  before_script:
    - CHCP 65001
    - pip install -r requirements.txt

  script:
    - echo "Run all tests"
    - pytest --alluredir=./allure-results

  artifacts:
    paths:
      - ./allure-results
    expire_in: 1 day

history_job:
  stage: history_copy
  script:
    - 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/24584062/jobs/artifacts/master/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - apk add unzip
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./allure-results
  allow_failure: true
  artifacts:
    paths:
      - ./allure-results
    expire_in: 1 day
  rules:
    - when: always

allure_job: # Название job
  stage: reports
  script:
     - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: deploy
  script:
    - mkdir public
    - mv ./allure-report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always
